---
title: "FTE Enrollment"
subtitle: "Full time equivalent enrollment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{full_time_equivalent}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(utDataStoR)
library(readr)
```

/* FTE Undergraduate by Credit Hour Type - Census
*/

FTE: Full-time Equivalent Enrollment

IPEDS calculates FTE twice a year. The Fall Enrollment survey and the 12 Month Enrollment survey.

USHE calculates FTE:

- Summer End of Term
- Fall 3rd Week Census
- Fall End of Term
- Spring 3rd Week Census
- Spring End of Term


```sql
SELECT b.term_desc,
       b.season,
          SUM(a.attempted_credits) as attmp_cred,
          ROUND(SUM(a.attempted_credits)/15, 2) as attmp_cred_fte,
          a.course_level_id,
          a.version_desc
     FROM export.student_section_version a
LEFT JOIN export.term b
       ON a.term_id = b.term_id
    WHERE a.is_enrolled = TRUE
      AND a.version_desc = 'Census'
      AND a.course_level_id = 'UG'
      AND DATE_PART('year', NOW()) - b.academic_year_code :: INT <= 5
GROUP BY a.course_level_id, b.season, b.term_desc, a.version_desc;
```


