---
title: "New Metrics"
author: "andrea"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## New Metric(s)

So, you think you need a new metric...

Metrics have several components

- Season
- Computation
- Partition
- Segment

For a description and examples of these, please see `vignettes/utMetrics.Rmd`

New metrics require varying degrees of work. The amount of work required for each request will determine how quickly the metrics can be created. #todo Should I provide an estimate of how long each level will take? Should I discuss the IE office working on them once a month? Should I mention that the IE office will make the final determination of what level the metric is?

- Level 1 - A new partition is needed for an existing computation
- Level 2 - A new computation is needed for a similar computation (for example the institution has Returned 4th Fall Cohort Retention, but you want to see Returned 5th Fall Cohort Retention)
- Level 3 - A new computation and partitions are needed

### Requesting New Metrics

To request a new metric please send a spreadsheet with the following columns to datablaze@utahtech.edu

Columns

- Requested Datapoint (Required) - The metric you want, you can word it in ways that makes sense to you
- Metric (Optional) - The official metric name, in the official metric format (Season Computation by Partition::Segment) feel free to put this in if you think you know what it is
- Computation (Optional) - The official computation name, if you know it
- Partition Field(s) (Optional) - The official partition name, if you know it
- Count and/or Rate (OIE only) - The metric value
- Year (OIE only) - The year of the metric
- Season (OIE only) - The season of the metric
- DRI (OIE only) - The directly responsible individual
- Source (OIE only) - Where did the data come from
- Issue (OIE only) - The name of the issue in utMetrics
- Notes (Optional) - Information you want the OIE office to know regarding the metric
