---
title: "Retention"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{retention}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Retention is a measure of how many students return to UT. By contrast, persistence is a measure of how many students continue their education at any university. The National Student Clearinghouse differentiates retention and persistence in the following way.

*Persistence rate is measured by the percentage of students who return to college at any institution for their second year, while retention rate represents the percentage of students who return to the same institution.*

This vignette will focus on the metrics involved in retention. The university's retention metrics can be broadly broken into two groups. Cohort retention and term-to-term retention.  

## Cohort retention

Degree seeking students are assigned a cohort when they enter the University. There are eight cohorts students are placed in 

- Full-time, Bachelors degree seeking, freshman
- Full-time, Bachelors degree seeking, transfer
- Part-time, Bachelors degree seeking, freshman
- Part-time, Bachelors degree seeking, transfer
- Full-time, Associates degree seeking, freshman
- Full-time, Associates degree seeking, transfer
- Part-time, Associates degree seeking, freshman
- Part-time, Associates degree seeking, transfer

Cohort retention metrics track these cohorts as they progress toward graduation. UT has eight cohort retention metrics. The denominator for this metric is the number of student within the cohort. The numerator for the metric is the number of students from the cohort who were enrolled as of census for the term indicated.

- Fall-to-spring cohort retention rate
- Fall-to-fall2 cohort retention rate 
- Fall-to-fall3 cohort retention rate 
- Fall-to-fall4 cohort retention rate

```{rsql}
    SELECT a.student_id,
           a.cohort_start_term_id,
           a.is_exclusion,
           -- Second fall return rate
           a.is_returned_next_fall,
           a.is_graduated_year_1,
           -- Third fall return rate
           a.is_returned_fall_3,
           a.is_degree_completer_2,
           -- Fourth fall return rate
           a.is_returned_fall_4,
           a.is_degree_completer_3,
           c.primary_major_desc,
           c.primary_degree_id,
           c.primary_degree_desc,
           d.college_abbrv,
           d.college_desc,
           e.first_name,
           e.last_name,
           e.gender_code,
           e.ipeds_race_ethnicity,
           e.is_veteran,
           e.is_international,
           e.is_athlete,
           e.is_first_generation
     FROM export.student_term_cohort a
LEFT JOIN export.term b
       ON b.term_id = a.cohort_start_term_id
LEFT JOIN export.student_term_level_version c
       ON c.student_id = a.student_id
      AND c.term_id = a.cohort_start_term_id
      AND c.is_enrolled
      AND c.is_primary_level
      AND c.is_census_version
LEFT JOIN export.academic_programs d
       ON d.program_id = c.primary_program_id
LEFT JOIN export.student e
       ON e.student_id = a.student_id
    WHERE b.season = 'Fall'
      AND a.cohort_desc = 'First-Time Freshman'
      AND substr(a.cohort_start_term_id, 1, 4)::int >= (SELECT substr(term_id, 1, 4)::int - 5
                                     FROM export.term
                                     WHERE is_current_term)

```


## Term-to-term

Term-to-term retention tracks all students (degree seeking and non-degree seeking) from academic term to term, regardless of their assigned cohort. The denominator for this metric is the number of students enrolled in an academic term. The numerator for this metric is the number of students still enrolled in a subsequent term. 

Term-to-term retention can be calculated on a fall-to-fall basis or a fall-to-spring basis with outcomes that indicate the status of a student.

Term-to-term outcomes include:

  - Associates: Student completed an associates credential.
  - Masters: Student completed a masters credential.
  - Dropped Out: Student did not enroll for subsequent term.
  - Stopped Out: Student temporarily withdraws from enrolling in subsequent terms.
  - Enrolled: Student is enrolled in the subsequent term.
  
```{sql}
   SELECT a.student_id,
          a.term_id,
          a.is_returned_next_spring,
          a.is_returned_next_fall,
          c.primary_major_desc,
          c.primary_degree_id,
          c.primary_degree_desc,
          d.college_abbrv,
          d.college_desc,
          e.first_name,
          e.last_name,
          e.gender_code,
          e.ipeds_race_ethnicity,
          e.is_veteran,
          e.is_international,
          e.is_athlete,
          e.is_first_generation,
          COALESCE(f.is_exclusion, FALSE) AS is_exclusion,
          COALESCE(f.cohort_start_term_id, 'None') AS cohort_start_term_id,
          COALESCE(f.cohort_desc, 'None') AS cohort_type
     FROM export.student_term_outcome a
LEFT JOIN export.term b
       ON b.term_id = a.term_id
LEFT JOIN export.student_term_level_version c
       ON c.student_id = a.student_id
      AND c.term_id = a.term_id
      AND c.is_enrolled
      AND c.is_primary_level
      AND c.is_census_version
LEFT JOIN export.academic_programs d
       ON d.program_id = c.primary_program_id
LEFT JOIN export.student e
       ON e.student_id = a.student_id
LEFT JOIN export.student_term_cohort f
       ON f.student_id = a.student_id
      AND f.cohort_desc IN ('First-Time Freshman', 'Transfer')
    WHERE b.season = 'Fall'
      AND substr(a.term_id, 1, 4)::int >= (SELECT substr(term_id, 1, 4)::int - 5
                                     FROM export.term
                                     WHERE is_current_term)
```
  

